name: unicorn-binance-local-depth-cache

channels:
  - lucit
  - conda-forge
  - defaults

dependencies:
  - python>=3.7
  - lucit::lucit-licensing-python>=1.8.2
  - lucit::unicorn-binance-rest-api>=2.5.0
  - lucit::unicorn-binance-websocket-api>=2.7.0
  - cython
  - requests>=2.31.0
