name: unicorn-binance-local-depth-cache

channels:
  - lucit
  - conda-forge
  - defaults

dependencies:
  - python>=3.7
  - lucit::lucit-licensing-python
  - lucit::unicorn-fy
  - lucit::unicorn-binance-rest-api
  - lucit::unicorn-binance-websocket-api
  - cython
  - requests
