blank_issues_enabled: true
contact_links:
  - name: UNICORN Devs Chat
    url: https://t.me/unicorndevs
    about: Chat to us about the UNICORN Binance Local Depth Cache and ask general questions.
  - name: UNICORN Binance Local Depth Cache Discussions
    url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache/discussions
    about: Ask general questions.
  - name: UNICORN Binance Local Depth Cache documentation
    url: https://unicorn-binance-local-depth-cache.docs.lucit.tech/
    about: The complete UNICORN Binance Local Depth Cache documentation.
  - name: Get Professional and Fast Support
    url: https://www.lucit.tech/get-support.html
    about: Contact the LUCIT Development Team.
  - name: Get a UNICORN Binance Suite License
    url: https://shop.lucit.services/software/unicorn-binance-suite
    about: LUCIT Online Shop