blank_issues_enabled: true
contact_links:
  - name: UNICORN Devs Chat
    url: https://t.me/unicorndevs
    about: Chat to us about the UNICORN Binance Local Depth Cache and ask general questions.
  - name: UNICORN Binance Local Depth Cache Discussions
    url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache/discussions
    about: Ask general questions.
  - name: UNICORN Binance Local Depth Cache documentation
    url: https://unicorn-binance-local-depth-cache.docs.lucit.tech/
    about: The complete UNICORN Binance Local Depth Cache documentation.
