name: Build and Publish Anaconda

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build_conda_packages:
    name: Build conda on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        exclude:
          - os: windows-2022
            python-version: "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Install Conda Tools
        run: |
          conda update --all
          conda install -c conda-forge conda-build
          conda install conda-verify
          conda install -c anaconda anaconda-client

      - name: Configure PATH
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install Python Tools
        run: |
          pip install setuptools wheel --upgrade       

      - name: Install macOS SDK (only on macOS)
        if: runner.os == 'macOS'
        run: |
          sudo mkdir -p /opt/MacOSX10.10.sdk
          sudo curl -L -o MacOSX10.10.sdk.tar.xz https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.10.sdk.tar.xz
          sudo tar -xJf MacOSX10.10.sdk.tar.xz -C /opt/

      - name: Set CONDA_BUILD_SYSROOT (only on macOS)
        if: runner.os == 'macOS'
        run: |
          echo "CONDA_BUILD_SYSROOT: /opt/MacOSX10.10.sdk # [osx]" > conda_build_config.yaml

      - name: Install Windows SDK and Build Tools (Windows only)
        if: runner.os == 'Windows'
        run: |
          choco install visualstudio2019buildtools --params "'/IncludeRecommended /IncludeOptional'"
          choco install windows-sdk-10.0 --version=10.0.22621.0
          setx CMAKE_GENERATOR "Visual Studio 16 2019" /M
          setx DISTUTILS_USE_SDK 1
          setx MSSdk 1
          setx INCLUDE "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um"
          setx LIB "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x64"

      - name: Configure CMAKE_PLAT und PATH (Windows only)
        if: runner.os == 'Windows'
        run: |
          set CMAKE_PLAT=x64
          echo "$CONDA/bin" >> $GITHUB_PATH
          echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin" >> $GITHUB_PATH

      - name: Setup Visual Studio Environment (Windows only)
        if: runner.os == 'Windows'
        run: |
          cmd.exe /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

      - name: "conda search: lucit::"
        run: |
          conda config --add channels conda-forge
          conda config --add channels lucit
          conda config --show channels
          conda search lucit::lucit-licensing-python
          conda search lucit::unicorn-binance-rest-api
          conda search lucit::unicorn-binance-websocket-api
          conda search lucit::unicorn-fy

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: .
          overwrite: False
          python-version: ${{ matrix.python-version }}
          user: lucit
          label: main
          token: ${{ secrets.ANACONDA_API_TOKEN }}
        env:
          PIP_VERBOSE: 1
          CONDA_VERBOSITY: 3
